<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! class_exists( 'WC_Payment_Gateway' ) ) {
    return;
}

/**
 * Class WC_Gateway_Ezdefi
 *
 * @extends WC_Payment_Gateway
 */
class WC_Gateway_Ezdefi extends WC_Payment_Gateway
{
    const EXPLORER_URL = 'https://explorer.nexty.io/tx/';

    public $api_url;

    public $api_key;

    public $currency;

    public $payment_method;

    public $api;

    public $db;

	/**
	 * Constructs the class
	 */
    public function __construct()
    {
        $this->set_general_property();

        $this->init_form_fields();

        $this->init_settings();

        $this->set_settings_value();

        $this->api = new WC_Ezdefi_Api( $this->api_url, $this->api_key );

        $this->db = new WC_Ezdefi_Db();

        $this->init_hooks();
    }

    public function process_admin_options() {
	    return parent::process_admin_options(); // TODO: Change the autogenerated stub
    }

	/**
	 * Set general property of class
	 */
    protected function set_general_property()
    {
	    $this->id = 'ezdefi';
	    $this->method_title = __( 'Pay with cryptocurrency', 'woocommerce-gateway-ezdefi' );
	    $this->method_description = __( 'Using BTC, ETH or any kinds of cryptocurrency. Handle by ezDeFi', 'woocommerce-gateway-ezdefi' );
	    $this->has_fields = true;
    }

	/**
	 * Set settings value
	 */
    protected function set_settings_value()
    {
	    $this->enabled = $this->get_option( 'enabled' );
	    $this->title = $this->get_option( 'title' );
	    $this->description = $this->get_option( 'description' );
	    $this->api_url = $this->get_option( 'api_url' );
	    $this->api_key = $this->get_option( 'api_key' );
	    $this->currency = $this->get_option( 'currency' );
	    $this->payment_method = $this->get_option( 'payment_method' );
    }

	/**
	 * Init hooks
	 */
    public function init_hooks()
    {
        global $woocommerce;

        if( is_object( $woocommerce ) && version_compare( $woocommerce->version, '3.7.0', '>=' ) ) {
	        add_action( 'woocommerce_before_thankyou', array(
		        $this, 'qrcode_section'
	        ) );
        } else {
	        add_filter( 'do_shortcode_tag', array(
                $this, 'prepend_woocommerce_checkout_shortcode'
            ), 10, 4 );
        }

	    add_action( 'wp_enqueue_scripts', array(
            $this, 'payment_scripts'
        ) );

        add_action( 'admin_enqueue_scripts', array(
            $this, 'admin_scripts'
        ) );

        add_action( 'woocommerce_api_' . $this->id, array(
            $this, 'gateway_callback_handle'
        ) );

	    add_action( 'woocommerce_update_options_payment_gateways_' . $this->id, array(
            $this, 'process_admin_options'
        ) );
    }

	/**
	 * Register needed scripts for admin
	 */
    public function admin_scripts()
    {
        if ( 'woocommerce_page_wc-settings' !== get_current_screen()->id ) {
            return;
        }

        wp_register_script( 'wc_ezdefi_tiptip', plugins_url( 'assets/js/jquery.tipTip.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
        wp_register_script( 'wc_ezdefi_validate', plugins_url( 'assets/js/jquery.validate.min.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
        wp_register_style( 'wc_ezdefi_select2', plugins_url( 'assets/css/select2.min.css', WC_EZDEFI_MAIN_FILE ) );
        wp_register_script( 'wc_ezdefi_select2', plugins_url( 'assets/js/select2.min.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
        wp_register_style( 'wc_ezdefi_admin', plugins_url( 'assets/css/ezdefi-admin.css', WC_EZDEFI_MAIN_FILE ) );
        wp_register_script( 'wc_ezdefi_admin', plugins_url( 'assets/js/ezdefi-admin.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
    }

	/**
	 * Init plugin setting fields
	 */
    public function init_form_fields()
    {
        $this->form_fields = require dirname( __FILE__ ) . '/admin/ezdefi-settings.php';
    }

	/**
	 * Add needed scripts for admin
	 */
    public function generate_settings_html( $form_fields = array(), $echo = true )
    {
        wp_enqueue_script( 'wc_ezdefi_tiptip', plugins_url( 'assets/js/jquery.tipTip.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
        wp_enqueue_script( 'wc_ezdefi_validate', plugins_url( 'assets/js/jquery.validate.min.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
        wp_enqueue_style( 'wc_ezdefi_select2', plugins_url( 'assets/css/select2.min.css', WC_EZDEFI_MAIN_FILE ) );
        wp_enqueue_script( 'wc_ezdefi_select2', plugins_url( 'assets/js/select2.min.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
        wp_enqueue_style( 'wc_ezdefi_admin', plugins_url( 'assets/css/ezdefi-admin.css', WC_EZDEFI_MAIN_FILE ) );
        wp_enqueue_script( 'wc_ezdefi_admin', plugins_url( 'assets/js/ezdefi-admin.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION, true );
        wp_localize_script( 'wc_ezdefi_admin', 'wc_ezdefi_data',
            array(
                'ajax_url' => admin_url( 'admin-ajax.php' )
            )
        );

        return parent::generate_settings_html($form_fields, $echo);
    }

	/**
     * Genereate HTMl for payment method setting field
     *
	 * @param $key
	 * @param $data
	 *
	 * @return false|string
	 */
    public function generate_method_settings_html( $key, $data )
    {
	    $field_key = $this->get_field_key( $key );

	    ob_start();
	    ?>
	    <tr valign="top">
            <th scope="row" class="titledesc">
                <label for="<?php echo esc_attr( $field_key ); ?>"><?php echo wp_kses_post( $data['title'] ); ?> <?php echo $this->get_tooltip_html( $data ); // WPCS: XSS ok. ?></label>
            </th>
            <td class="forminp">
                <fieldset>
                    <input name="<?php echo $field_key; ?>[amount_id]" id="<?php echo $field_key; ?>[amount_id]" type="checkbox" class="" value="1" <?php echo ( isset( $this->payment_method['amount_id'] ) && $this->payment_method['amount_id'] === '1' ) ? 'checked' : '' ;?>>
                    <label for="<?php echo $field_key; ?>[amount_id]"><?php echo __( 'Pay with any crypto wallet', 'woocommerce-gateway-ezdefi' ); ?></label>
                    <p class="description"><?php echo __( 'This method will adjust payment amount of each order by an acceptable number to help payment gateway identifying the uniqueness of that order.', 'woocommerce-gateway-ezdefi' ); ?></p>
                </fieldset>
                <fieldset>
                    <input name="<?php echo $field_key; ?>[ezdefi_wallet]" id="<?php echo $field_key; ?>[ezdefi_wallet]" type="checkbox" class="" value="1" <?php echo ( isset( $this->payment_method['ezdefi_wallet'] ) && $this->payment_method['ezdefi_wallet'] === '1' ) ? 'checked' : '' ;?>>
                    <label for="<?php echo $field_key; ?>[ezdefi_wallet]"><?php echo __( 'Pay with ezDeFi wallet', 'woocommerce-gateway-ezdefi' ); ?></label>
                    <p class="description"><?php echo __( 'This method is more powerful when amount uniqueness above method reaches allowable limit. Users just need to install ezDeFi wallet then import their private key to pay using qrCode.', 'woocommerce-gateway-ezdefi' ); ?></p>
                </fieldset>
            </td>
        </tr>
	    <?php

	    return ob_get_clean();
    }

	/**
     * Validate payment method setting field
     *
	 * @param $key
	 * @param $value
	 *
	 * @return array|string
	 */
    public function validate_method_settings_field( $key, $value ) {
	    if( ! is_array( $value ) ) {
		    return '';
	    }

	    foreach( $value as $i => $v ) {
		    $value[$i] = $v;
	    }

	    return $value;
    }

	/**
     * Genereate HTMl for currency setting field
     *
	 * @param $key
	 * @param $data
	 *
	 * @return false|string
	 */
    public function generate_currency_settings_html( $key, $data )
    {
        $field_key = $this->get_field_key( $key );

        ob_start();
        ?>
        <tr valign="top">
            <th scope="row" class="titledesc">
                <label for="<?php echo esc_attr( $field_key ); ?>"><?php echo wp_kses_post( $data['title'] ); ?> <?php echo $this->get_tooltip_html( $data ); // WPCS: XSS ok. ?></label>
            </th>
            <td class="forminp">
                <table id="wc-ezdefi-currency-settings-table" class="widefat striped">
                    <thead>
                        <tr>
                            <th scope="col" class="sortable-zone">
                                <span class="dashicons dashicons-editor-help help-tip"></span>
                            </th>
                            <th scope="col" class="logo"></th>
                            <th scope="col" class="name"><?php echo __( 'Name', 'woocommerce-gateway-ezdefi' ); ?></th>
                            <th scope="col" class="discount"><?php echo __( 'Discount', 'woocommerce-gateway-ezdefi' ); ?></th>
                            <th scope="col" class="lifetime"><?php echo __( 'Expiration (minutes)', 'woocommerce-gateway-ezdefi' ); ?></th>
                            <th scope="col" class="wallet"><?php echo __( 'Wallet Address', 'woocommerce-gateway-ezdefi' ); ?></th>
                            <th scope="col" class="block-confirm"><?php echo __( 'Block Confirmation', 'woocommerce-gateway-ezdefi' ); ?></th>
                            <th scope="col" class="decimal"><?php echo __( 'Decimal', 'woocommerce-gateway-ezdefi' ); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if( ! empty( $this->currency ) && is_array( $this->currency ) ) : ?>
                            <?php foreach( $this->currency as $index => $c ) : ?>
                                <tr>
                                    <td class="sortable-handle">
                                        <span class="dashicons dashicons-menu"></span>
                                    </td>
                                    <td class="logo">
                                        <img src="<?php echo isset( $c['logo'] ) ? $c['logo'] : '' ;?>" class="ezdefi-currency-logo" alt="">
                                    </td>
                                    <td class="name">
                                        <input class="currency-symbol" type="hidden" value="<?php echo isset( $c['symbol'] ) ? $c['symbol'] : '' ;?>" name="<?php echo $field_key . '[' . $index . '][symbol]'; ?>]">
                                        <input class="currency-name" type="hidden" value="<?php echo isset( $c['name'] ) ? $c['name'] : '' ;?>" name="<?php echo $field_key . '[' . $index . '][name]'; ?>]">
                                        <input class="currency-logo" type="hidden" value="<?php echo isset( $c['logo'] ) ? $c['logo'] : '' ;?>" name="<?php echo $field_key . '[' . $index . '][logo]'; ?>">
                                        <input class="currency-desc" type="hidden" value="<?php echo isset( $c['desc'] ) ? $c['desc'] : '' ;?>" name="<?php echo $field_key . '[' . $index . '][desc]'; ?>">
                                        <input class="currency-chain" type="hidden" value="<?php echo ( isset( $c['chain'] ) ) ? $c['chain'] : ''; ?>" name="<?php echo $field_key . '[' . $index . '][chain]'; ?>">
                                        <div class="view">
                                            <span><?php echo isset( $c['name'] ) ? $c['name'] : '' ;?></span>
                                            <div class="actions">
                                                <a href="" class="editBtn"><?php echo __( 'Edit', 'woocommerce-gateway-ezdefi' ); ?></a>
                                                |
                                                <a href="" class="deleteBtn"><?php echo __( 'Delete', 'woocommerce-gateway-ezdefi' ); ?></a>
                                            </div>
                                        </div>
                                        <div class="edit">
                                            <select name="<?php echo $field_key . '[' . $index . '][select]'; ?>" class="select-select2">
                                                <?php if( isset( $c['symbol'] ) ) : ?>
                                                    <option value="<?php echo $c['symbol'];?>" selected="selected"><?php echo $c['symbol'];?></option>
                                                <?php endif; ?>
                                            </select>
                                            <div class="actions">
                                                <a href="" class="cancelBtn"><?php echo __( 'Cancel', 'woocommerce-gateway-ezdefi' ); ?></a>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="discount">
                                        <div class="view">
                                            <?php echo ( isset( $c['discount'] ) && ! empty( $c['discount'] ) ) ? $c['discount'] : '0' ;?>%
                                        </div>
                                        <div class="edit">
                                            <input type="number" name="<?php echo $field_key . '[' . $index . '][discount]'; ?>" value="<?php echo isset( $c['discount'] ) ? $c['discount'] : 0 ;?>"><span> %</span>
                                        </div>
                                    </td>
                                    <td class="lifetime">
                                        <div class="view">
                                            <?php echo isset( $c['lifetime'] ) ? ($c['lifetime'] / 60) . 'm' : '' ;?>
                                        </div>
                                        <div class="edit">
                                            <input type="number" name="<?php echo $field_key . '[' . $index . '][lifetime]'; ?>" value="<?php echo isset( $c['lifetime'] ) ? ($c['lifetime'] / 60) : '' ;?>"><span> minutes</span>
                                        </div>
                                    </td>
                                    <td class="wallet">
                                        <div class="view">
                                            <?php echo isset( $c['wallet'] ) ? $c['wallet'] : '' ;?>
                                        </div>
                                        <div class="edit">
                                            <input type="text" class="currency-wallet" placeholder="Wallet Address" name="<?php echo $field_key . '[' . $index . '][wallet]'; ?>" value="<?php echo isset( $c['wallet'] ) ? $c['wallet'] : '' ;?>">
                                        </div>
                                    </td>
                                    <td class="block_confirm">
                                        <div class="view">
                                            <?php echo isset( $c['block_confirm'] ) ? $c['block_confirm'] : '' ;?>
                                        </div>
                                        <div class="edit">
                                            <input type="number" name="<?php echo $field_key . '[' . $index . '][block_confirm]'; ?>" value="<?php echo isset( $c['block_confirm'] ) ? $c['block_confirm'] : '' ;?>">
                                        </div>
                                    </td>
                                    <td class="decimal">
                                        <div class="view">
			                                <?php echo isset( $c['decimal'] ) ? $c['decimal'] : '' ;?>
                                        </div>
                                        <div class="edit">
                                            <input type="number" class="currency-decimal" name="<?php echo $field_key . '[' . $index . '][decimal]'; ?>" value="<?php echo isset( $c['decimal'] ) ? $c['decimal'] : '' ;?>">
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else : ?>
                            <tr class="editing">
                                <td class="sortable-handle">
                                    <span class="dashicons dashicons-menu"></span>
                                </td>
                                <td class="logo">
                                    <img src="<?php echo plugins_url( 'assets/images/newsd-icon.png', WC_EZDEFI_MAIN_FILE ); ?>" class="ezdefi-currency-logo" alt="">
                                </td>
                                <td class="name">
                                    <input class="currency-symbol" type="hidden" value="newsd" name="<?php echo $field_key . '[0][symbol]'; ?>]">
                                    <input class="currency-name" type="hidden" value="NewSD" name="<?php echo $field_key . '[0][name]'; ?>]">
                                    <input class="currency-logo" type="hidden" value="<?php echo plugins_url( 'assets/images/newsd-icon.png', WC_EZDEFI_MAIN_FILE ); ?>" name="<?php echo $field_key . '[0][logo]'; ?>">
                                    <input class="currency-desc" type="hidden" value="NewSD - Stablecoin token for payment" name="<?php echo $field_key . '[0][desc]'; ?>">
                                    <input class="currency-chain" type="hidden" value="eth" name="<?php echo $field_key . '[0][chain]'; ?>">
                                    <div class="view">
                                        <span>NewSD</span>
                                        <div class="actions">
                                            <a href="" class="editBtn">Edit</a>
                                            |
                                            <a href="" class="deleteBtn">Delete</a>
                                        </div>
                                    </div>
                                    <div class="edit">
                                        <select name="<?php echo $field_key . '[0][select]'; ?>" class="select-select2">
                                            <option value="newsd" selected="selected">NewSD</option>
                                        </select>
                                        <div class="actions">
                                            <a href="" class="cancelBtn">Cancel</a>
                                        </div>
                                    </div>
                                </td>
                                <td class="discount">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[0][discount]'; ?>" value="0"><span> %</span>
                                    </div>
                                </td>
                                <td class="lifetime">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[0][lifetime]'; ?>" value=""><span> m</span>
                                    </div>
                                </td>
                                <td class="wallet">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="text" class="currency-wallet" placeholder="Wallet Address" name="<?php echo $field_key . '[0][wallet]'; ?>" value="">
                                    </div>
                                </td>
                                <td class="block_confirm">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[0][block_confirm]'; ?>" value="">
                                    </div>
                                </td>
                                <td class="decimal">
                                    <div class="view">
                                        4
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[0][decimal]'; ?>" value="4">
                                    </div>
                                </td>
                            </tr>
                            <tr class="editing">
                                <td class="sortable-handle">
                                    <span class="dashicons dashicons-menu"></span>
                                </td>
                                <td class="logo">
                                    <img src="<?php echo plugins_url( 'assets/images/bitcoin-icon.png', WC_EZDEFI_MAIN_FILE ); ?>" class="ezdefi-currency-logo" alt="">
                                </td>
                                <td class="name">
                                    <input class="currency-symbol" type="hidden" value="btc" name="<?php echo $field_key . '[1][symbol]'; ?>]">
                                    <input class="currency-name" type="hidden" value="Bitcoin" name="<?php echo $field_key . '[1][name]'; ?>]">
                                    <input class="currency-logo" type="hidden" value="<?php echo plugins_url( 'assets/images/bitcoin-icon.png', WC_EZDEFI_MAIN_FILE ); ?>" name="<?php echo $field_key . '[1][logo]'; ?>">
                                    <input class="currency-desc" type="hidden" value="" name="<?php echo $field_key . '[1][desc]'; ?>">
                                    <input class="currency-chain" type="hidden" value="btc" name="<?php echo $field_key . '[1][chain]'; ?>">
                                    <div class="view">
                                        <span>Bitcoin</span>
                                        <div class="actions">
                                            <a href="" class="editBtn">Edit</a>
                                            |
                                            <a href="" class="deleteBtn">Delete</a>
                                        </div>
                                    </div>
                                    <div class="edit">
                                        <select name="<?php echo $field_key . '[1][select]'; ?>" class="select-select2">
                                            <option value="btc" selected="selected">Bitcoin</option>
                                        </select>
                                        <div class="actions">
                                            <a href="" class="cancelBtn">Cancel</a>
                                        </div>
                                    </div>
                                </td>
                                <td class="discount">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[1][discount]'; ?>" value="0"><span> %</span>
                                    </div>
                                </td>
                                <td class="lifetime">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[1][lifetime]'; ?>" value=""><span> m</span>
                                    </div>
                                </td>
                                <td class="wallet">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="text" class="currency-wallet" placeholder="Wallet Address" name="<?php echo $field_key . '[1][wallet]'; ?>" value="">
                                    </div>
                                </td>
                                <td class="block_confirm">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[1][block_confirm]'; ?>" value="">
                                    </div>
                                </td>
                                <td class="decimal">
                                    <div class="view">
                                        8
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[1][decimal]'; ?>" value="8">
                                    </div>
                                </td>
                            </tr>
                            <tr class="editing">
                                <td class="sortable-handle">
                                    <span class="dashicons dashicons-menu"></span>
                                </td>
                                <td class="logo">
                                    <img src="<?php echo plugins_url( 'assets/images/ethereum-icon.png', WC_EZDEFI_MAIN_FILE ); ?>" class="ezdefi-currency-logo" alt="">
                                </td>
                                <td class="name">
                                    <input class="currency-symbol" type="hidden" value="eth" name="<?php echo $field_key . '[2][symbol]'; ?>]">
                                    <input class="currency-name" type="hidden" value="Ethereum" name="<?php echo $field_key . '[2][name]'; ?>]">
                                    <input class="currency-logo" type="hidden" value="<?php echo plugins_url( 'assets/images/ethereum-icon.png', WC_EZDEFI_MAIN_FILE ); ?>" name="<?php echo $field_key . '[2][logo]'; ?>">
                                    <input class="currency-desc" type="hidden" value="" name="<?php echo $field_key . '[2][desc]'; ?>">
                                    <input class="currency-chain" type="hidden" value="eth" name="<?php echo $field_key . '[2][chain]'; ?>">
                                    <div class="view">
                                        <span>Ethereum</span>
                                        <div class="actions">
                                            <a href="" class="editBtn">Edit</a>
                                            |
                                            <a href="" class="deleteBtn">Delete</a>
                                        </div>
                                    </div>
                                    <div class="edit">
                                        <select name="<?php echo $field_key . '[2][select]'; ?>" class="select-select2">
                                            <option value="eth" selected="selected">Ethereum</option>
                                        </select>
                                        <div class="actions">
                                            <a href="" class="cancelBtn">Cancel</a>
                                        </div>
                                    </div>
                                </td>
                                <td class="discount">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[2][discount]'; ?>" value="0"><span> %</span>
                                    </div>
                                </td>
                                <td class="lifetime">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[2][lifetime]'; ?>" value=""><span> m</span>
                                    </div>
                                </td>
                                <td class="wallet">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="text" class="currency-wallet" placeholder="Wallet Address" name="<?php echo $field_key . '[2][wallet]'; ?>" value="">
                                    </div>
                                </td>
                                <td class="block_confirm">
                                    <div class="view">
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[2][block_confirm]'; ?>" value="">
                                    </div>
                                </td>
                                <td class="decimal">
                                    <div class="view">
                                        8
                                    </div>
                                    <div class="edit">
                                        <input type="number" name="<?php echo $field_key . '[2][decimal]'; ?>" value="8">
                                    </div>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="8">
                                <a href="" class="addBtn button button-secondary">
                                    <?php echo __( 'Add Currency', 'woocommerce-gateway-ezdefi' ); ?>
                                </a>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </td>
        </tr>
        <?php

        return ob_get_clean();
    }

	/**
	 * Validate currency setting field
	 *
	 * @param $key
	 * @param $value
	 *
	 * @return array|string
	 */
    public function validate_currency_settings_field( $key, $value )
    {
        if( ! is_array( $value ) ) {
            return '';
        }

        foreach( $value as $i => $v ) {
            $v['lifetime'] = $v['lifetime'] * 60;
            $value[$i] = array_map( 'sanitize_text_field', $v );
        }

        return $value;
    }

	/**
	 * Add needed scripts for payment process
	 */
    public function payment_scripts()
    {
	    if ( 'no' === $this->enabled ) {
		    return;
	    }

	    wp_register_style( 'wc_ezdefi_checkout', plugins_url( 'assets/css/ezdefi-checkout.css', WC_EZDEFI_MAIN_FILE ), array(), WC_EZDEFI_VERSION );
	    wp_enqueue_style( 'wc_ezdefi_checkout' );
	    wp_register_script( 'wc_ezdefi_checkout', plugins_url( 'assets/js/ezdefi-checkout.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery' ), WC_EZDEFI_VERSION );
	    wp_enqueue_script( 'wc_ezdefi_checkout' );

	    wp_register_style( 'wc_ezdefi_qrcode', plugins_url( 'assets/css/ezdefi-qrcode.css', WC_EZDEFI_MAIN_FILE ), array(), WC_EZDEFI_VERSION );
	    wp_register_script( 'wc_ezdefi_qrcode', plugins_url( 'assets/js/ezdefi-qrcode.js', WC_EZDEFI_MAIN_FILE ), array( 'jquery', 'jquery-ui-tabs', 'clipboard' ), WC_EZDEFI_VERSION );
	    wp_localize_script( 'wc_ezdefi_qrcode', 'wc_ezdefi_data',
		    array(
			    'ajax_url' => admin_url( 'admin-ajax.php' ),
                'checkout_url' => wc_get_checkout_url()
		    )
	    );
    }

    public function get_icon() {
        $icon_html = '<div id="wc-ezdefi-icon">';
	    foreach( $this->currency as $i => $c ) {
	        if($i < 3) {
		        $icon_html .= '<img src="' . $c['logo'] . '" />';
	        }
        }
        $icon_html .= '</div>';

	    return apply_filters( 'woocommerce_gateway_icon', $icon_html, $this->id );
    }

	/**
	 * Add payment field on checkout page
	 */
	public function payment_fields() {
        $description = $this->get_description();

        ob_start(); ?>
        <div id="wc-wzdefi-checkout">
            <?php
                $cart = WC()->cart;
                $total = $cart->get_totals()['total'];
                $currency = get_woocommerce_currency();

                echo wpautop( wp_kses_post( $description ) );
                echo $this->currency_select_html( $total, $currency );
            ?>
            <input type="hidden" name="wc_ezdefi_currency" id="wc_ezdefi_currency">
        </div>
	    <?php echo ob_get_clean();
    }

	/**
     * Validate field before process payment
     *
	 * @return bool
	 */
	public function validate_fields() {
		if( ! isset( $_POST['wc_ezdefi_currency'] ) || empty( $_POST['wc_ezdefi_currency'] ) ) {
		    wc_add_notice( '<strong>' . __( 'Please select currency', 'woocommerce-gateway-ezdefi' ) . '</strong>', 'error' );
		    return false;
        }

		return true;
    }

	/**
     * Handle creating payment
     *
	 * @param int $order_id
	 *
	 * @return array
	 */
    public function process_payment( $order_id ) {
        $order = wc_get_order( $order_id );

	    $order->update_status('on-hold', __( 'Awaiting ezdefi payment', 'woocommerce-gateway-ezdefi' ) );

	    $symbol = sanitize_text_field( $_POST['wc_ezdefi_currency'] );

	    $currency_data = $this->db->get_currency_option( $symbol );

	    if( ! $currency_data ) {
		    wc_add_notice( 'Fail. Please try again or contact shop owner', 'error' );

            $order->update_status( 'failed' );

            return array(
                'result'   => 'fail',
                'redirect' => '',
            );
        }

	    $order->add_meta_data( 'ezdefi_currency', $symbol );
	    $order->save_meta_data();

	    return array(
		    'result' => 'success',
		    'redirect' => $this->get_return_url( $order )
	    );
    }

	/**
     * Preprend QRcode section to woocommerce_checkout_shortcode (older version)
     *
	 * @param $output
	 * @param $tag
	 *
	 * @return string
	 */
    public function prepend_woocommerce_checkout_shortcode( $output, $tag )
    {
        global $wp;

	    if ( $tag != 'woocommerce_checkout' ) {
		    return $output;
	    }

	    $order_id = $wp->query_vars['order-received'];

	    if( ! $order_id ) {
	        return $output;
        }

	    $prepend = $this->qrcode_section( $order_id );

	    $output = $prepend . $output;

	    return $output;
    }

	/**
     * Add QRcode section to thankyou page
     *
	 * @param $order_id
	 */
    public function qrcode_section( $order_id )
    {
        $order = wc_get_order( $order_id );

	    if( ( $order->get_payment_method() != $this->id ) || ( $order->get_status() === 'completed' ) || ( $order->get_status() === 'failed' ) ) {
		    return;
	    }

	    $symbol = $order->get_meta( 'ezdefi_currency' );

	    $selected_currency = $this->db->get_currency_option( $symbol );

	    if( ! $selected_currency ) {
	        return;
        }

	    $payment_data = array(
		    'uoid' => $order_id,
		    'total' => $order->get_total(),
		    'ezdefi_payment' => ( $order->get_meta( 'ezdefi_payment' ) ) ? $order->get_meta( 'ezdefi_payment' ) : ''
	    );

	    wp_enqueue_style( 'wc_ezdefi_qrcode' );
	    wp_enqueue_script( 'wc_ezdefi_qrcode' );

        ob_start();?>
            <div id="wc_ezdefi_qrcode">
                <script type="application/json" id="payment-data"><?php echo json_encode( $payment_data ); ?></script>
                <?php echo $this->currency_select_html( $order->get_total(), $order->get_currency(), $selected_currency ); ?>
                <div class="wc-ezdefi-loader"></div>
                <div class="ezdefi-payment-tabs" style="display: none">
                    <ul>
                        <?php
                            foreach( $this->payment_method as $key => $value ) {
                                echo '<li>';
                                switch ($key) {
                                    case 'amount_id' :
                                        echo '<a href="#'.$key.'" id="tab-'.$key.'"><span class="large-screen">' . __( 'Pay with any crypto wallet', 'woocommerce-gateway-ezdefi' ) . '</span><span class="small-screen">' . __( 'Any crypto wallet', 'woocommerce-gateway-ezdefi' ) . '</span></a>';
                                        break;
                                    case 'ezdefi_wallet' :
                                        echo '<a href="#'.$key.'" id="tab-'.$key.'" style="background-image: url('.plugins_url( 'assets/images/ezdefi-icon.png', WC_EZDEFI_MAIN_FILE ).')"><span class="large-screen"> ' . __( 'Pay with ezDeFi wallet', 'woocommerce-gateway-ezdefi' ) . '</span><span class="small-screen" style="background-image: url('.plugins_url( 'assets/images/ezdefi-icon.png', WC_EZDEFI_MAIN_FILE ).')"> ' . __( 'ezDeFi wallet', 'woocommerce-gateway-ezdefi' ) . '</span></a>';
                                        break;
                                }
                                echo '</a></li>';
                            }
                        ?>
                    </ul>
	                <?php foreach( $this->payment_method as $key => $value ) : ?>
                        <div id="<?php echo $key;?>" class="ezdefi-payment-panel"></div>
	                <?php endforeach; ?>
                </div>
            </div>
        <?php echo ob_get_clean();
    }

    public function currency_select_html( $total, $currency, $selected_currency = array() )
    {
        ob_start(); ?>
        <div class="currency-select">
		    <?php
		    $to = implode(',', array_map(function ( $currency ) {
			    return $currency['symbol'];
		    }, $this->currency ) );
		    $exchanges = $this->api->get_token_exchanges(
			    $total,
			    $currency,
			    $to
		    );
		    ?>
		    <?php foreach( $this->currency as $c ) : ?>
                <div class="currency-item__wrap">
                    <div class="currency-item <?php echo ( ! empty( $selected_currency['symbol'] ) && $c['symbol'] === $selected_currency['symbol'] ) ? 'selected' : ''; ?>" data-symbol="<?php echo $c['symbol']; ?>" >
                        <div class="item__logo">
                            <img src="<?php echo $c['logo']; ?>" alt="">
                            <?php if( ! empty( $c['desc'] ) ) : ?>
                                <div class="item__desc">
                                    <?php echo $c['desc']; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="item__text">
                            <div class="item__price">
							    <?php
							    $discount = ( intval($c['discount']) > 0) ? $c['discount'] : 0;
							    $index = array_search( $c['symbol'], array_column( $exchanges, 'token' ) );
							    $amount = $exchanges[$index]['amount'];
							    $amount = $amount - ( $amount * ( $discount / 100 ) );
							    echo number_format( $amount, 8 );
							    ?>
                            </div>
                            <div class="item__info">
                                <div class="item__symbol">
								    <?php echo $c['symbol']; ?>
                                </div>
                                <div class="item__discount">
                                    - <?php echo $discount; ?>%
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
		    <?php endforeach; ?>
        </div>
        <?php return ob_get_clean();
    }

	/**
	 * Handle callback from gateway when payment DONE
	 */
	public function gateway_callback_handle()
	{
	    if( isset( $_GET['uoid'] ) && isset( $_GET['paymentid'] ) ) {
		    $order_id = sanitize_key( $_GET['uoid'] );
		    $paymentid = sanitize_key( $_GET['paymentid'] );

		    return $this->process_payment_callback( $order_id, $paymentid );
        }

		if(
            isset( $_GET['value'] ) && isset( $_GET['explorerUrl'] ) &&
            isset( $_GET['currency'] ) && isset( $_GET['id'] ) &&
            isset( $_GET['decimal'] )
		) {
			$value = sanitize_key( $_GET['value'] );
			$decimal = sanitize_key( $_GET['decimal'] );
			$value = $value / pow( 10, $decimal );
			$explorerUrl = sanitize_text_field( $_GET['explorerUrl'] );
			$currency = sanitize_text_field( $_GET['currency'] );
			$id = sanitize_key( $_GET['id'] );

			return $this->process_transaction_callback( $value, $explorerUrl, $currency, $id);
        }
	}

	public function process_transaction_callback( $value, $explorerUrl, $currency, $id )
    {
        $response = $this->api->get_transaction( $id );

	    if( is_wp_error( $response ) ) {
		    wp_send_json_error();
	    }

	    $response = json_decode( $response['body'], true );

	    if( $response['code'] != 1 ) {
	        wp_send_json_error();
        }

	    $transaction = $response['data'];

	    if( $transaction['status'] != 'ACCEPTED' ) {
	        wp_send_json_error();
        }

	    $data = array(
            'amount_id' => number_format( $value, 12, '.', '' ),
            'currency' => $currency,
            'explorer_url' => $explorerUrl,
        );

        $this->db->add_exception( $data );

        wp_send_json_success();
    }

    public function process_payment_callback( $order_id, $paymentid )
    {
	    global $woocommerce;

	    $order_id = substr( $order_id, 0, strpos( $order_id,'-' ) );
	    $order = wc_get_order( $order_id );

	    if( ! $order ) {
		    wp_send_json_error();
	    }

	    $response = $this->api->get_ezdefi_payment( $paymentid );

	    if( is_wp_error( $response ) ) {
		    wp_send_json_error();
	    }

	    $payment = json_decode( $response['body'], true );

	    if( $payment['code'] < 0 ) {
		    wp_send_json_error();
	    }

	    $payment = $payment['data'];

	    $status = $payment['status'];

	    if( $status === 'PENDING' || $status === 'EXPIRED' ) {
	        wp_send_json_error();
        }

	    if( isset( $payment['amountId'] ) && $payment['amountId'] === true ) {
		    $amount_id = $payment['originValue'];
	    } else {
		    $amount_id = $payment['value'] / pow( 10, $payment['decimal'] );
	    }

	    $amount_id = number_format( $amount_id, 12, '.', '' );

	    $currency = $payment['currency'];

	    $exception_data = array(
		    'status' => strtolower($status),
		    'explorer_url' => (string) self::EXPLORER_URL . $payment['transactionHash']
	    );

	    $wheres = array(
		    'amount_id' => $amount_id,
		    'currency' => (string) $currency,
		    'order_id' => (int) $order_id
	    );

	    if( isset( $payment['amountId'] ) && $payment['amountId'] = true ) {
		    $wheres['payment_method'] = 'amount_id';
	    } else {
		    $wheres['payment_method'] = 'ezdefi_wallet';
	    }

	    if( $status === 'DONE' ) {
		    $order->update_status( 'completed' );
		    $woocommerce->cart->empty_cart();
		    $this->db->update_exception( $wheres, $exception_data );

		    if( ! isset( $payment['amountId'] ) || ( isset( $payment['amountId'] ) && $payment['amountId'] != true ) ) {
		        $this->db->delete_exception_by_order_id( $wheres['order_id'] );
            }
	    } elseif( $status === 'EXPIRED_DONE' ) {
		    $this->db->update_exception( $wheres, $exception_data );
	    }

	    wp_send_json_success();
    }
}